### UNDERSTANDING FAISS

In [1]:
pip install faiss-cpu

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install sentence-transformers


Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('FAISS_text.csv')

In [5]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [6]:
#converting the text to vectors using embeddings

In [7]:
from sentence_transformers import SentenceTransformer


In [8]:
#using hugging face encoder 
encoder =  SentenceTransformer('all-mpnet-base-v2')
vectors = encoder.encode(df.text)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [9]:
vectors

array([[-0.00247388,  0.03626732, -0.05290462, ..., -0.09152353,
        -0.03970002, -0.04330488],
       [-0.0335726 ,  0.00980523, -0.03250127, ..., -0.05165467,
         0.02245887, -0.03156181],
       [-0.01865327, -0.04051312, -0.01235392, ...,  0.00610578,
        -0.07179645,  0.02773848],
       ...,
       [-0.0006645 ,  0.04252122, -0.05645503, ...,  0.01315469,
        -0.03183562, -0.04357669],
       [-0.03317156,  0.03252461, -0.02484838, ...,  0.01174415,
         0.05747119,  0.00571026],
       [-0.00166395,  0.00413829, -0.04597078, ...,  0.02008528,
         0.05656244, -0.00161593]], shape=(8, 768), dtype=float32)

In [10]:
vectors.shape

(8, 768)

In [11]:
vectors[0]

array([-2.47388380e-03,  3.62673216e-02, -5.29046208e-02, -2.17348225e-02,
        1.41723491e-02, -1.01589889e-03,  2.23636273e-02,  3.65196653e-02,
        3.80901210e-02,  5.22017805e-03, -3.00865676e-02,  2.05448573e-03,
        1.08503001e-02, -8.49088430e-02, -5.57265664e-03, -6.06598295e-02,
        2.32009194e-03, -1.51409041e-02,  1.20671391e-02,  1.98904742e-02,
       -1.27935773e-02, -2.72811316e-02, -3.31878588e-02,  3.40652629e-03,
        8.41171946e-03, -1.94853917e-02,  4.88132276e-02,  2.24118754e-02,
        4.53467369e-02, -5.90891689e-02, -9.13183168e-02, -1.22333888e-03,
       -4.05046344e-02,  8.67175497e-03,  1.26565294e-06, -1.92451719e-02,
       -3.20658907e-02, -4.08172123e-02,  8.79176781e-02, -1.52631188e-02,
        1.09908860e-02, -4.47977744e-02, -4.74826060e-03,  3.52632962e-02,
        1.31070958e-02,  1.09944083e-02, -3.45755485e-03,  9.12349373e-02,
        5.68808466e-02,  4.82893772e-02, -4.51438921e-03,  3.58450599e-02,
       -2.44209487e-02, -

In [12]:
dim  = vectors.shape[1]

In [13]:
dim

768

In [14]:
import faiss
index =  faiss.IndexFlatL2(dim)

In [15]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x00000206263F6880> >

In [16]:
index.add(vectors)

In [17]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [88]:
search_query = "An apple a day keeps doctors away"

In [100]:
vec = encoder.encode(search_query)

In [101]:
vec.shape

(768,)

In [102]:
import numpy as np

In [103]:
S_vec = np.array(vec).reshape(1,-1)

In [104]:
S_vec.shape

(1, 768)

In [105]:
index.search(S_vec,k=2)

(array([[1.3522654, 1.7111093]], dtype=float32), array([[1, 0]]))

In [106]:
dis,I = index.search(S_vec , k=2)

In [107]:
dis

array([[1.3522654, 1.7111093]], dtype=float32)

In [108]:
I

array([[1, 0]])

In [109]:
df.iloc[I[0]]


text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health